---
triple:          'arm64-apple-darwin'
binary-path:     prodcons
relocations:
  - { offsetInCU: 0x26, offset: 0x26, size: 0x8, addend: 0x0, symName: _put, symObjAddr: 0x0, symBinAddr: 0x100003C2C, symSize: 0x54 }
  - { offsetInCU: 0x3F, offset: 0x3F, size: 0x8, addend: 0x0, symName: _fill_ptr, symObjAddr: 0x1018, symBinAddr: 0x100008000, symSize: 0x0 }
  - { offsetInCU: 0x5B, offset: 0x5B, size: 0x8, addend: 0x0, symName: _use_ptr, symObjAddr: 0x101C, symBinAddr: 0x100008004, symSize: 0x0 }
  - { offsetInCU: 0x70, offset: 0x70, size: 0x8, addend: 0x0, symName: _count, symObjAddr: 0x1020, symBinAddr: 0x100008008, symSize: 0x0 }
  - { offsetInCU: 0x93, offset: 0x93, size: 0x8, addend: 0x0, symName: _buffer, symBinAddr: 0x10000800C, symSize: 0x0 }
  - { offsetInCU: 0xB4, offset: 0xB4, size: 0x8, addend: 0x0, symName: _empty, symBinAddr: 0x100008038, symSize: 0x0 }
  - { offsetInCU: 0x113, offset: 0x113, size: 0x8, addend: 0x0, symName: _fill, symBinAddr: 0x100008068, symSize: 0x0 }
  - { offsetInCU: 0x128, offset: 0x128, size: 0x8, addend: 0x0, symName: _mutex, symBinAddr: 0x100008098, symSize: 0x0 }
  - { offsetInCU: 0x175, offset: 0x175, size: 0x8, addend: 0x0, symName: _put, symObjAddr: 0x0, symBinAddr: 0x100003C2C, symSize: 0x54 }
  - { offsetInCU: 0x199, offset: 0x199, size: 0x8, addend: 0x0, symName: _get, symObjAddr: 0x54, symBinAddr: 0x100003C80, symSize: 0x54 }
  - { offsetInCU: 0x1C1, offset: 0x1C1, size: 0x8, addend: 0x0, symName: _producer, symObjAddr: 0xA8, symBinAddr: 0x100003CD4, symSize: 0xB0 }
  - { offsetInCU: 0x1F7, offset: 0x1F7, size: 0x8, addend: 0x0, symName: _consumer, symObjAddr: 0x158, symBinAddr: 0x100003D84, symSize: 0xCC }
  - { offsetInCU: 0x23B, offset: 0x23B, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x224, symBinAddr: 0x100003E50, symSize: 0xC8 }
...
